### ISSUE TITLE
Is there a way to extend the service?

### ISSUE THREAD

**Issue by kellyselden** [kaliber5/ember-window-mock#14]
I would like to do some custom `scrollTo` stuff on the service:

```js
import Service from 'ember-window-mock/somewhere';

export default Service.extend({
  scrollTo() {
    // custom stuff
  }
});
```

Is this possible with the way you are using factories?

**Comment by simonihmig** [comment]
Hm, both services do not extend from `Ember.Service`, as the "real" service is just the plain `window` object. The mock wraps an ES6 proxy around that to intercept certain methods/props. 

I guess you could wrap it in another Proxy to fake the `scrollTo`, though that seems a bit weird (one proxy behind another). 

But maybe there should be some way to extend the proxy handler with some custom traps here? https://github.com/kaliber5/ember-window-mock/blob/master/addon-test-support/-private/services/window.js#L9-L23

**Comment by simonihmig** [comment]
Closing this, as the current implementation does not use services anymore, and you should be able to "clobber" the mocked `window`...
