### ISSUE TITLE
Automatically run mockWindow(this) in beforeEach

### ISSUE THREAD

**Issue by erichonkanen** [kaliber5/ember-window-mock#16]
Hey so I added this to a sizable codebase and running `ember test` about 30+ tests fail across multiple files because of unknown injection. It seems like if this package automatically ran `mockWindow(this)` in `beforeEach._super()` it would make life a lot easier :D

**Comment by simonihmig** [comment]
Any idea how this could work? I don't have any access to your tests `before*` hooks, so I don't see how this could be made automatically!?

**Comment by kellyselden** [comment]
I don't think this addon should do that. We wrap beforeEach of integration tests and do this type of work in there:

```js
import {
  moduleForComponent,
  test
} from 'ember-qunit';
import { mockWindow } from 'ember-window-mock';

function _moduleForComponent(name, description, callbacks) {
  let { beforeEach } = callbacks;

  callbacks.beforeEach = function() {
    mockWindow(this);

    if (beforeEach) {
      return beforeEach.apply(this, arguments);
    }
  };

  return moduleForComponent(name, description, callbacks);
}

export {
  _moduleForComponent as moduleForComponent,
  test
};
```

**Comment by erichonkanen** [comment]
@kellyselden very nice... thanks
