### ISSUE TITLE
delete window.prop regression?

### ISSUE THREAD

**Issue by kellyselden** [kaliber5/ember-window-mock#20]
My tests started failing that involved `delete window._satellite;`. It appears it no longer goes through the `set` logic, so all `get`s still have the `target`s property intact.

**Comment by kellyselden** [comment]
Here is some reference code https://github.com/kellyselden/ember-metrics-adobe-dtm/pull/8

**Comment by simonihmig** [comment]
Hm, not sure what is going on... if I understand this correctly, you set a prop on `window`, `delete` it, but it's still there, right?

Was this working before?

**Comment by kellyselden** [comment]
Yep, I confirmed it came in with 0.1.3 https://github.com/kellyselden/ember-metrics-adobe-dtm/issues/5#issuecomment-343632785

**Comment by simonihmig** [comment]
@kellyselden published the fix as 0.1.4, hope it works for you!

**Comment by kellyselden** [comment]
It's back to working. Thanks a lot!
