### ISSUE TITLE
Figure out a way to not need to call mockWindow in each test

### ISSUE THREAD

**Issue by rwwagner90** [kaliber5/ember-window-mock#23]
Discussed this some in slack with @simonihmig but we didn't come up with any definitive solution. The main problem with calling `mockWindow` in each test, for me, is if I use it in an addon, then someone consumes my addon, they may not know about this requirement, and it could break their tests and be hard for them to figure out how to fix.

**Comment by simonihmig** [comment]
Just C&P from Slack, so the latest discussion does not get lost 😉

![image](https://user-images.githubusercontent.com/1325249/33028581-989c0ed0-ce16-11e7-8862-8f49aafc6e32.png)
