### ISSUE TITLE
Problem binding function

### ISSUE THREAD

**Issue by kellyselden** [kaliber5/ember-window-mock#26]
This line is problematic https://github.com/kaliber5/ember-window-mock/blob/master/addon-test-support/-private/services/window.js#L20

It breaks this case:

```js
let spy = sinon.spy();
window.scrollTo = spy;
spy.reset // a funtion
window.scrollTo.reset // undefined
```

I'm not sure how to fix it.

**Comment by simonihmig** [comment]
Hm, I see. All this Proxy stuff has some delicate pitfalls... 🙄

Would you be able to submit a failing test? I have some idea I could try out...
