### ISSUE TITLE
Illegal invocation of dispatchEvent in test

### ISSUE THREAD

**Issue by TopsyCM** [kaliber5/ember-window-mock#36]
I have a call to `window.dispatchEvent` which gives an `Illegal invocation` error when run in tests. It works otherwise. The call is made from a bound function as follows:

```
  window: service(),

  init() {
    this._super(...arguments);
    let broadcast = bind(this, this.broadcast);
    get(this, 'someService').on('someEvent', broadcast);
  },

  broadcast() {
    let window = get(this, 'window');
    window.dispatchEvent(new Event('event-name'));
  },
```

Is there something else I need to be doing to maintain the correct context?

**Comment by simonihmig** [comment]
@TopsyCM thanks for reporting. Sounds like this should work, will have to investigate. The `Proxy` used in the mocked `window` sometimes leads to unexpected (for me) side effects...

If you are interested in contributing, a PR with a failing test would be awesome! Something along the lines of https://github.com/chrislopresto/ember-freestyle/pull/100. But not required...

**Comment by TopsyCM** [comment]
I have not worked with Proxies before, so everything is unexpected (for me). I will try to repro the failure in a test if time allows.

**Comment by TopsyCM** [comment]
Looks like the extra event wrapping is not necessary to cause the error.
