### ISSUE TITLE
Support for localStorage

### ISSUE THREAD

**Issue by alisdair** [kaliber5/ember-window-mock#43]
This addon is really useful, thanks for making it! 🎉 

It might be helpful to have a mock for `localStorage`, similar to the `location` one: implementing the normal API, against an ephemeral store. This would make it easier for me to avoid state leaking across tests.

Would that make sense to you? Wanted to check before working on a PR.

**Comment by simonihmig** [comment]
> This addon is really useful, thanks for making it! 🎉

Thank you!

> Would that make sense to you? Wanted to check before working on a PR.

Sure, I think that would be a great addition!

I quickly googled this: https://github.com/letsrock-today/mock-local-storage. I don't know if that would be directly usable (seems to be made for node), or at least serve as an inspiration...

The idea is that this would still work?

```js
import window form 'ember-window-mock';

...

window.localStorage.setItem('foo', 'bar');
assert.equal(window.localStorage.getItem('foo'), 'bar');
```

i.e. you still have a hash to store values, but this get's reseted by calling this addon's `reset` function, to neat leak between tests, right?

**Comment by alisdair** [comment]
Thanks for your quick reply.

Yep, that's the idea exactly! The mock-local-storage module might not quite work (as you said, it's made for node) but it's basically the same implementation I was thinking of.

Hoping to work on this in the next few days.
