### ISSUE TITLE
starting in v0.7.0, setting window.onerror results in TypeError: Illegal invocation

### ISSUE THREAD

**Issue by ctaylor-nurx** [kaliber5/ember-window-mock#438]
Ember version 3.12.0 / cli 3.12.1

I have a logging service trying to set `window.onerror` in the init block to catch errors that bubble all the way up to the browser window and log them.

The following code was working until v0.7.0 of ember-window-mock:
`window.onerror = (...nestedArgs) => this.onWindowError(...nestedArgs);`

I can get it to work just fine (as above) in v0.6.0 and lower. I've tried various bindings and whatnot to try to resolve the error, but to no avail. All of the following also cause the same issue.
```
window.onerror = this.onWindowError;
window.onerror = this.onWindowError.bind(window);
window.onerror = this.OnWindowError.bind(this);
window.onerror = function (...args) { debugger; };
window.onerror = function (msg, url, line, column, error){
  this.onWindowError(msg, url, line, column, error);
};
window.onerror = (msg, url, line, column, error) => this.onWindowError(msg, url, line, column, error);
```

I'm not sure what change caused the issue... looking at the commits between 0.6.0 and 0.7.0 mostly just were various dependency bumps and embroider support.

**Comment by simonihmig** [comment]
Sorry for the late response, I must have missed this.

To be clear: are you setting `onerror` as part of some mocking, so in tests after you have called `setupWindowMock()`, or does it fail when running the app normally (without mocking)?

**Comment by ctaylor-nurx** [comment]
Thanks, this actually did fix the issue.
