### ISSUE TITLE
Export function to setup window mock reset in new ember-qunit tests

### ISSUE THREAD

**Issue by makepanic** [kaliber5/ember-window-mock#57]
Thanks for maintaining this addon.

The recent version of ember-qunit [applies functions on the qunit hooks](https://github.com/emberjs/ember-qunit#setup-tests) to setup ember specific stuff:

```js
import { setupTest } from 'ember-qunit';

module('SidebarController', function(hooks) {
  setupTest(hooks);
  // ...
});
```

`ember-window-mock` could export a function like `setupWindowMockTest(hooks)` which adds calls to `reset` in the hooks beforeEach, afterEach functions.

e.g. something like:
```js
import {setupWindowMockTest} from 'ember-window-mock';

module('SidebarController', function(hooks) {
  setupWindowMockTest(hooks);
  // ...
});
```

This is mostly cosmetic but reduces the work a user has to do to use window mock in testing.
If this is an addition to window mock that you want to have, I can open a PR.

**Comment by simonihmig** [comment]
@makepanic sorry for the late answer, I missed this somehow. Your suggestion makes sense, PR certainly welcome!
