### ISSUE TITLE
Tries to create new Proxy of null

### ISSUE THREAD

**Issue by makepanic** [kaliber5/ember-window-mock#72]
Hi,
I've upgrade from 0.3.0 to 0.5.0 and saw failing tests.
Investigating further, it looks like window-mock tries to create a Proxy of `null`.

I was trying to use window-mock on `window.onbeforeunload`. This is initially `null` if nothing is registered.

![20181005-141016](https://user-images.githubusercontent.com/1205444/46534758-9c2ca580-c8a9-11e8-975d-349f1f696d89.png)

This causes the code to create a `new Proxy(null, ...)` which isn't valid:

![20181005-141031](https://user-images.githubusercontent.com/1205444/46534815-c2524580-c8a9-11e8-8049-92680c7fbb2c.png)

Is this an issue in how I am using window-mock or an actual bug?

**Comment by simonihmig** [comment]
Hm, looks like a bug, thanks for reporting.

Seems the condition in the first screen needs an additional `&& window[name] !== null`, because of, well, JavaScript... (`typeof null` is 'object')

Need a Hacktoberfest shirt, i.e. up for a PR? 😉
