### ISSUE TITLE
IE 11 support

### ISSUE THREAD

**Issue by buschtoens** [kaliber5/ember-window-mock#80]
I know, that ember-window-mock can't fully work in IE11, because of the missing `Proxy` support. However, it would be nice, if it wouldn't crash the full test suite. 😅 

Since `new URL` is not available in IE11, this line crashes everything:

https://github.com/kaliber5/ember-window-mock/blob/ada959b92f104c875066140be3c3ca7f34110f7d/addon-test-support/-private/mock/location.js#L25

There's potentially more, but I haven't yet debugged it. Would you accept a PR that make ember-window-mock play a bit nicer with IE11?

**Comment by simonihmig** [comment]
Sure!

Maybe we could also export a test helper like `isSupported()`, that tells you if the current browser has support for the DOM APIs required by ember-window-mock, to know when to skip certain tests?

**Comment by buschtoens** [comment]
Cool. 😊 

I thought about something along these lines as well. `isSupported` could just be a constant, I guess.

```js
import { IS_SUPPORTED } from 'ember-window-mock':

(IS_SUPPORTED ? test : skip)('some test', function(assert) {

});
```

**Comment by simonihmig** [comment]
Yeah, that could work!

**Comment by elwayman02** [comment]
@buschtoens @simonihmig there is a polyfill for proxy, is there a way to optionally pull in this polyfill for IE11?

https://github.com/GoogleChrome/proxy-polyfill

**Comment by buschtoens** [comment]
Considering we deem this polyfill "feature-complete enough", I am happy to take over / to lead / lobby for / help wherever I can with the implementation. @ClarkSource has business requirements for running CI in IE11 and anything that aligns with that I can get on our road map! 🗺😄

**Comment by elwayman02** [comment]
It looks like this addon uses `has` and `deleteProperty` from the Proxy API, which isn't currently supported by the polyfill. I'm not sure if it's possible to add that to the polyfill, but that's where we'd need to start I think.

**Comment by elwayman02** [comment]
Any further thoughts on this @buschtoens?

**Comment by elwayman02** [comment]
Seems like this can be closed now that IE is deprecated.

**Comment by buschtoens** [comment]
Absolutely, yes! 🥳

![](https://media.giphy.com/media/Del9OqEskdrC8/giphy.gif)
