### ISSUE TITLE
Issue mocking Notification

### ISSUE THREAD

**Issue by makepanic** [kaliber5/ember-window-mock#85]
Hi,

I'm seeing an issue when trying to use window-mock with `Notification.requestPermission`.

The issue is that `typeof Notification` is `function` where window-mock returns a [bound version of it](https://github.com/kaliber5/ember-window-mock/blob/master/addon-test-support/-private/window.js#L30).

![20181120-131139](https://user-images.githubusercontent.com/1205444/48774609-0028f300-eccb-11e8-865e-08236912e128.png)

But somehow creating a bound instance of Notification erases its "static" methods.

![20181120-131119](https://user-images.githubusercontent.com/1205444/48774638-18007700-eccb-11e8-8da7-a8bf5ac91155.png)

I think we could fix this by adding "Notification"  to the list of `proxyFactory` users. If that's ok, I can open a PR for it.

edit: nvm. I think that doesn't really work

**Comment by simonihmig** [comment]
@makepanic I think I have found a fix here: #86 

Could you try that branch to confirm it fixes your problem?

**Comment by makepanic** [comment]
Tried it for the error I've encountered and it looks fine.
The proxied static method is now there and usable.

Thanks for the quick fix

**Comment by simonihmig** [comment]
Good to hear, thanks for the quick feedback!

**Comment by simonihmig** [comment]
published 0.5.3!
